### ISSUE TITLE
Hi man, there is an asset problem

### ISSUE THREAD

**Issue by dnqbob** [Pinkthoth/openra-swp#3]
![1](https://user-images.githubusercontent.com/13763394/181520894-178dd6e0-34ea-4176-99df-4d752f57bc35.PNG)
We find this picture in newst version of this mod/game which has a high possibility using TA's asset:
![TA1](https://user-images.githubusercontent.com/13763394/181522773-49790643-a5fd-4d5a-9a17-c52b770fc2d4.gif)

We are not asset cops but could you please at least add "EoralMilk" at `Authors.txt` and pont out which asset is used. After all,  EoralMilk spent several on making this asset, it should be not hard on just reminding others about the creator of assets.

**Comment by dnqbob** [comment]
Sorry I just see it on master branch

**Comment by Pinkthoth** [comment]
Hello there

EoralMilk should be in the Credits.txt, but I will check that. He has
released his assets on C&C Mod Haven on Discord, so I assumed they were
free to use. I am also using his hospital as well, but I will eventually
replace them with my own assets.

Regards
Pinkthoth

to 28. heinäk. 2022 klo 17.13 dnqbob ***@***.***> kirjoitti:

**Comment by dnqbob** [comment]
> so I assumed they were
free to use. I am also using his hospital as well, but I will eventually
replace them with my own assets.

As long as you credit, there is no problem for you to use them. I have found it in `master` branch, the `main` branch was pretty confusing at that time.
